### ISSUE TITLE
Documentation of @Component.bind

### ISSUE THREAD

**Issue by sectore** [MikeRyan52/angular-decorators#10]
First of all: Thanks for this awesome project!

Just a suggestion about the docs. It seems there are some missing notes about `bindToController` of Angular `1.3` (not `1.4`, which is [already documented](https://github.com/MikeRyan52/angular-decorators#binding-element-attributes-to-the-controller) ) by using [@Component.bind](https://github.com/MikeRyan52/angular-decorators/blob/master/src/util/decorate-directive.js#L8). 

``` js
// Decorator for using Angular 1.3 only
@Component({
    selector: 'my-component',
    bind: {
        'myProp: =renamedProp',
        '@anotherAttribute'
    }
})
class MyComponentCtrl
```

This becomes:

``` js
.directive('myComponent', function(){
    return {
        restrict: 'E',
        controller: function MyComponentCtrl{ },
        controllerAs: 'myComponent',
        scope: {
            'myProp' : '=renamedProp',
            'anotherAttribute' : '@'
        },
        bindToController: true
    }
})
```

PS. Just noticed that an example is described at [0.1x docs](https://github.com/MikeRyan52/angular-decorators/blob/v0.1.x/README.md#component) . It would be nice to take it over to [latest doc](https://github.com/MikeRyan52/angular-decorators/blob/master/README.md), because Angular `1.3` is still alive :) 

Thanks again!

-Jens

**Comment by MikeRyanDev** [comment]
Hi Jens,

You are definitely right, this needs to be documented. I'll get it in the docs tonight. 

Thanks!
Mike

**Comment by sectore** [comment]
Mike, thanks for such a fast response / fix :)

-Jens
