### ISSUE TITLE
constant and value

### ISSUE THREAD

**Issue by msuntharesan** [MikeRyan52/angular-decorators#11]
Is it possible to add aliases to `constant` and `value`?

**Comment by MikeRyanDev** [comment]
Yup, shouldn't be a problem. I'll see about getting this in tonight.

**Comment by msuntharesan** [comment]
Wow thats fast. Thanks. 
Also I want find out is it possible to add factory function without a class. Right now I have to call `myModule.publish().factory('name' , ['dep', fn])`.

Ex:

``` js
function apiFactory($http) {
  var anObject = {} //this is a dynamically generated object;
  return anObject;
}

myModule.publish().factory('name' , ['$http', apiFactory]);
```

**Comment by MikeRyanDev** [comment]
Unfortunately, there's no great way of doing that with these decorators. If you wanted to use them for consistency, the best you could do at the moment is this:

``` js
import {Factory, Inject, Module} from 'angular-decorators';

@Factory('name')
@Inject('$http')
class NameFactory{
   static create(deps){
      let [$http] = deps;
      let anObject = {};

      return anObject;
   }
}

export default Module('my-module', []).add(NameFactory);
```

Otherwise, I'd stick with publishing the module and using the vanilla factory function.
