### ISSUE TITLE
Unit tests fail with PhantomJS

### ISSUE THREAD

**Issue by tb** [MikeRyan52/angular-decorators#13]
I have setup sample app at https://github.com/tb/angular-webpack-es7-decorators

It uses `angular-decorators`, works with `babel?stage=1`. Tests `gulp test` are running in Chrome, but not in PhantomJS.

There error I get is:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of the parameter associated to the object.
  at /Users/tb/projects/angular-webpack-es7-decorators/spec.bundle.js:32201 <- webpack:///(webpack)/~/node-libs-browser/~/crypto-browserify/rng.js:14:0
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.12 secs / 0 secs)
```

I see other projects have similar issue, for example https://github.com/angular-class/angular2-webpack-starter/issues/45

Any ideas how to fix it?

**Comment by MikeRyanDev** [comment]
No solutions off of the top of my head. Dependency tree that is breaking this: angular-decorators -> metawriter -> reflect-metadata -> crypto

Unfortunately, the browser version of crypto ([browserify-crypto](https://github.com/crypto-browserify/crypto-browserify)) doesn't work correctly in phantomjs v1.9. I would raise the issue there and see if they have any ideas.

**Comment by MikeRyanDev** [comment]
Closing this since I can't really do much about it on my end. Please touch back if you find a solution!
