### ISSUE TITLE
Join forces with similar projects?

### ISSUE THREAD

**Issue by btford** [MikeRyan52/angular-decorators#2]
I've seen a couple projects with similar goals:
- https://github.com/crescware/toccata
- https://github.com/bendrucker/angular-annotation-decorator

Would be great to combine efforts!

There's also this related issue on angular/angular.js: https://github.com/angular/angular.js/issues/10007

/cc @MikeRyan52 @armorik83

**Comment by okunokentaro** [comment]
Got it. :+1:

**Comment by timkindberg** [comment]
Also: https://github.com/innit/angular-decorate @robwormald

**Comment by MikeRyanDev** [comment]
Also @pbastowski

**Comment by timkindberg** [comment]
I've been using https://github.com/hannahhoward/a1atscript and contributing to it as well for a large new project. It's not without bugs but it's got well written code and a solid test bed.

**Comment by timkindberg** [comment]
And there is @pbastowski https://github.com/pbastowski/angular2-now

**Comment by egor-smirnov** [comment]
I noticed these issues in Angular 1.x tracker - https://github.com/angular/angular.js/labels/hotlist%3A%20ng2migration. This gives hope that annotations for Angular 1.x will be implemented in project produced by Angular team.

It's nice that bindings from Angular2 will be ported to Angular 1.5 (see https://github.com/angular/angular.js/issues/12198 and https://github.com/angular/angular.js/issues/12197).

**Comment by hannahhoward** [comment]
FYI this may happen... https://github.com/ngUpgraders/ng-forward .... nothing yet, but the collaborators on these projects are talking.

**Comment by MikeRyanDev** [comment]
Yup, if anyone has interest in a converged project please check out the ng-forward project.
