### ISSUE TITLE
Passing injected dependencies to link method of the component

### ISSUE THREAD

**Issue by egor-smirnov** [MikeRyan52/angular-decorators#7]
Let's assume I have code like this:

``` javascript
@Component({
    selector: 'some-component'
})
@Template({inline: template})
@Inject('$rootScope')

class SomeComponent {
  constructor($rootScope) {
    this.$rootScope = $rootScope;
    ...
  }

  static link(scope) {
    this.$rootScope.$on(...)  <--- here I don't have access to this.$rootScope because method is static
  }
}
```

As you can see, the problem is that I don't know how to inject something into static method of class. And in my particular case I am not able to use `scope` parameter of `link` function, so this is not the solution.

Do you have something in mind about possible ways to achieve injection into static link function? 

My mind can't generate anything more or less elegant.

P.S. For the moment I workarounded this with usage of `scope.$root` like this:

``` javascript

class SomeComponent {
  static link(scope) {
    scope.$root.$on(...)
  }
}
```

But I was lucky as my injected dependency was $rootScope, not something like $timeout.

**Comment by MikeRyanDev** [comment]
An ugly but useable workaround is to require the instance of your controller:

``` js
import {Require, Component, Inject} from 'angular-decorators';

@Component({ selector : 'some-selector' })
@Require('someSelector')
@Inject('$rootScope')
class SomeSelectorCtrl{
   constructor($rootScope){
      this.$rootScope = $rootScope;
   }
   static link(scope, el, attrs, requires){
      let [someSelector] = requires; // someSelector is an instance of SomeSelectorCtrl

      someSelector.$rootScope.$on(...);
   }
}
```

**Comment by egor-smirnov** [comment]
Thank you, this should work. Going to think about more 'user-friendly' solution later.
